version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/reactblock/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directories:
      - "/ui/pages/reactblocking/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
