name: Sample CI
on: [ push, pull_request ]

jobs:
  test-functions:
    name: Test functions/reactblock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'functions/reactblock/requirements.txt'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: functions/reactblock
      - name: Run tests if test_main.py exists
        run: |
          if [ -f "test_main.py" ]; then
            echo "Running tests with test_main.py"
            pytest
          else
            echo "No test_main.py found, skipping tests"
          fi
        working-directory: functions/reactblock
      - name: Verify function starts
        run: |
          timeout 30s bash -c '
            python main.py > output.log 2>&1 &
            PID=$!
            while ! grep -q "running at port 8081" output.log 2>/dev/null; do
              sleep 1
            done
            echo "✅ Application started successfully"
            kill $PID 2>/dev/null || true
          ' || {
            echo "❌ Application failed to start"
            cat output.log 2>/dev/null || echo "No output log found"
            exit 1
          }
        working-directory: functions/reactblock

  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'ui/pages/reactblocking/package-lock.json'
      - name: Install dependencies
        run: npm ci
        working-directory: ui/pages/reactblocking
      - name: Build React app
        run: npm run build
        working-directory: ui/pages/reactblocking